### ISSUE TITLE
Change audit strategy

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/glados#37]
The current selection strategy for content auditing needs to be updated.  The priority for auditing should be as follows.

- Query `content_id` table and order by number of audits that have been performed (fewer first, more last)
- Secondary ordering by creation date `content_id.created_at` in descending order (newer first, older last)

This ensures that we focus on auditing the latest stuff first that has never been audited, and then once everything in the database has been audited, it starts focusing on re-auditing things with priority on the newest of those items.

**Comment by perama-v** [comment]
I can take a look at this next. It seems to make sense to do this before # 36

**Comment by perama-v** [comment]
Requires #52, and will then become:

1. Query `content_key` table
2. Secondary ordering by `content_key.created_at`

**Comment by pipermerriam** [comment]
I think this is now fixed.
