### ISSUE TITLE
OverlayContentKey use does not include selector

### ISSUE THREAD

**Issue by perama-v** [pipermerriam/glados#47]
## Description

A `T: OverlayContentKey` passed into a function does not have a way to get the actual content_key (e.g., the bytes including the selector).  

Use of `.into()`, which is the counterpart to `From` and has the following implementation.
```rs
// trin/ethportal-api/src/types/content_key.rs
impl From<HistoryContentKey> for Vec<u8> {
    fn from(val: HistoryContentKey) -> Self {
        val.as_ssz_bytes()
    }
}
```
This gets the bytes of the enum, using the derived `Encode`
```rs
/// A content key in the history overlay network.
#[derive(Clone, Debug, Decode, Encode, Eq, PartialEq)]
#[ssz(enum_behaviour = "union")]
pub enum HistoryContentKey {
```
Which does not include the selector.

**Comment by perama-v** [comment]
This is incorrect. The selector is included, contrary to the above. This must be courtesy of `.as_ssz_bytes()` using the `impl Serialize for HistoryContentKey` in `ethportal-api` which incorporates the selector.

**Comment by pipermerriam** [comment]
:+1: I'm pretty sure we have our `Union` type's setup so that they end up accounting for the selector values.

**Comment by perama-v** [comment]
Ok thanks for the tip!
