### ISSUE TITLE
Table hierarchy

### ISSUE THREAD

**Issue by perama-v** [pipermerriam/glados#52]
### Description

Need to decide if `content_id` (current) or `content_key` are the subject matter for operations in `glados`.

Highest ranked item:
- Trin: `content_key`. In `ethportal-api` we define `OverlayContentKey` which has the method `content_id`. So content_key is the top level
- Glados: `content_id`. In `glados/entities` we define a table `contentid` with a "has_many" `content_key`s relationship. So the content_id is the top level.

This seems to be inverted in glados. 

### Discussion

- What are the downsides to staying with `content_id`?
    - Mental overhead: Function names are `content_key`-centric
    - Additional lookups: block data -> content_key table -> content_id table

**Comment by pipermerriam** [comment]
Within the portal network we have content keys and content ids.  All content keys map to a single content id.  It is *possible* for multiple content keys to map to the same content id.  For this reason, I think that the I think that `block_data -> content_key -> content_id` is the most correct.

**Comment by perama-v** [comment]
Is the explanation for a content id duplicate:

There are potentially many overlay networks, which may choose content key definitions that are the same as an existing overlay network content key definition?

**Comment by pipermerriam** [comment]
Currently there are no parts of our network designs that have a `content_id` that has multiple `content_key` values, however, it's a design space we've intentionally left open and that may be used in the future.

One example of a situation where at some future date we might have multiple content keys that point to the same content_id would be:

- block bodies are identified by the key `0xXX<block-hash>`
- individual transactions within a block body are identified by the key `0xZZ<block-hash><tx-index>`

Both of these keys would map to the same `content_id` since nodes that store the block body can also respond to requests for an individual transaction from the block.  Different content keys, same content id.  For this reason, I think that in glados, we should be pointing primarily at the content_key with our foreign keys.

**Comment by perama-v** [comment]
Given these things, I would favour removing `content_id` from the database.  

One can always readily obtain the `content_id` by `sha3(content_key)` so there does not seem to be a reason to store it. 
The only reason I can see to keep it is in a scenario of starting with a `content_id` and wanting a `content_key`. However, this is both unlikely and problematic due to the potential for many `content_key`s for one `content_id`.

**Comment by pipermerriam** [comment]
The method for deriving `content_id` from `content_key` isn't universal, and depends on the content key type and what network, so I believe that at minimum, we want to add a field to the `ContentKey` model that has the `content_id`, but I also think it's fine (and my minor preference) to just keep the `ConentId` table around.

**Comment by perama-v** [comment]
If we are using `OverlayContentKey` from the `ethportal-api` then the `content_id` is always available (even though under the mechanics for different types  e.g., HistoryContentKey, ?StateContentKey,. etc). 

So there will never be a `T: OverlayContentKey` that doesn't have a `.content_id()` method.

**Comment by perama-v** [comment]
That said, I'm happy to keep it. I'll move forward with `content_id` tables with foreign keys as pointing to the `content_key` table

**Comment by perama-v** [comment]
I am going to close this issue for now for the following reasons:

- Keeping the current database structure does not roadblock progress.
- Direct modification of existing migrations (as in #55) would break long-running databases.
- Exploration of adding a new database migration to invert the foreign key relationship was unfruitful.

Here is the approach I was trying:
```rs
/// Inverts the foreign key relationship of content_key and content_id tables.
    ///
    /// Effectively removing content_id from the content_key table, and
    /// making content_id table aware of the content_key table.
    ///
    /// 1. Add required column (add content_key column to content_id table)
    /// 2. Create data
    ///     - The the foreign key in the new column is found by searching with the old fk.
    ///     - content_id.content_key = content_key.id if (content_key.content_id == content_id.id)
    /// 3. Remove not-requried column (remove content_id column from content_key table)
    ///
    /// Changes:
    /// - content_id table
    ///     - id: `i32`
    ///     - <change: add> content_key: `i32` (foreign key)
    ///     - content_id: `Vec<u8>`
    /// - content_key table
    ///     - id: `i32`
    ///     - <change: remove> content_id: `i32` (foreign key)
    ///     - content_key: `Vec<u8>`
    ///     - created_at: `DateTime<Utc>`
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // 1.
        let foreign_key_content_key = TableForeignKey::new()
            .name("FK_content_id_content_key")
            .from_tbl(ContentId::Table)
            .from_col(ContentId::ContentKey)
            .to_tbl(ContentKey::Table)
            .to_col(ContentKey::Id)
            .on_delete(ForeignKeyAction::Cascade)
            .on_update(ForeignKeyAction::Cascade)
            .to_owned();

        manager.alter_table(
            Table::alter()
                .table(ContentKey::Table)
                .add_foreign_key(&foreign_key_content_key)
                .to_owned()
        ).await?;

        // 2.
        todo!("Unclear how to proceed.");

        // 3.
        manager.alter_table(
            Table::alter()
                .table(ContentKey::Table)
                .drop_column(OriginalContentKey::ContentId)
                .to_owned()
        ).await?;
```
