### ISSUE TITLE
Make auditing compatible with different sub-protocols

### ISSUE THREAD

**Issue by perama-v** [pipermerriam/glados#68]
## Description

The auditing is specific to the History network. If it were to be made agnostic to sub-protocols then this will save work later on.
The cause of the current limitation is that we:
1. ✅ (`glados-monitor`) Follow a Portal node and record content keys/ids/metadata  in a glados-db
2. ✅ (`glados-audit`) Employ different strategies to decide on what glados-db content to audit.
3. (`glados-audit`) presume all content in glados-db are from the History sub-protocol and send `HistoryContentKey`s in the mpsc audit channel. ❌ Would not handle other sub-protocols.
4. (`glados-audit`) For each task in the audit channel, perform a `portal_historyRecursiveFindContent` request to a Portal Node.  ❌  Would not handle other sub-protocols.

## Solution
In three parts:
### Record the sub-protocol in the glados-db. 
Currently we do this with the execution metadata tables, for header, body & receipts but not EpochAccumulator. Options are:
A. Treat these tables as sub-protocol identifiers. Would need to add a table for EpochAccumulator items, and any items added for different sub-protocols
B. Add a new table for sub-protocol

Option B seems cleaner because in the event of a second sub-protocol, you do not need to check multiple tables to find matches.

### Make mpsc channel more broad

The channel currently handles `HistoryContentKey`. It could send database IDs in the channel. 

### Lookup sub-protocols at audit time

The audit task can operate as follows:
- 1. Look up what sub-protocol the item is from
- 2. Call the appropriate `portal_*RecursiveFindContent`
- 3. Log the appropriate metadata (based on the sub-protocol)

## Considerations

Any key entered into the glados-db may clash with an identical key on a different sub-protocol. To handle this,
keys should AFAICT have a many-to-one relationship with a sub-protocol identifier. 

- Decide on a key to audit
    - Look up what sub-protocol it is from
    - Audit on that sub-protocol (E.g., `portal_historyRecursiveFindContent`)
    - Record audit result for that content
- Glados monitor creates a second key that is identical (to the above) but on a different subprotocol
    - Need to store the key, but in a way so as to not inherit the audit from the similar key 
        - Perhaps by storing the sub-protocol along with the audit date/result data.
    
Not yet sure of the best way to a organise a sub-protocol table / foreign key to achieve this.

## Alternatives

Maybe there are other better solutions. 
- ? Separate database for sub-protocols

**Comment by pipermerriam** [comment]
I think it may make sense to simplify our schema as follows.

```
table Content:
    id: i32 database primary key
    protocol_id: <sub protocol id>
    content_key: <full content key>
    content_id: <32 byte content_id>
    first_available_at: <datetime>
```

we would want a multi column unique clause for `(protocol_id, content_key, content_id)`

This combines the existing ContentID and ContentKey tables into a single unified table and I think it satisfies all of our needs and makes our database a lot simpler.

I'm fine with the *quick* way of getting here, which would be to destroy the existing tables and create new tables and ignore doing any data migration.

**Comment by perama-v** [comment]
> I'm fine with the _quick_ way of getting here, which would be to destroy the existing tables and create new tables and ignore doing any data migration.

Say no more! 👟 👟 

I interpreted `first_available_at` as: "first available to glados-audit", as in time that the item was added to glados-db. 
So if we add to glados-db via backfilling, old chain data will have a recent timestamp for `first_available_at`.
