### ISSUE TITLE
How to handle Portal node timeouts

### ISSUE THREAD

**Issue by perama-v** [pipermerriam/glados#92]
### Description
Should a timeout be entered into the database as a failed audit or logged as an error?

`glados-audit` can either recieve
- A Portal node can respond with "no content" ("0x") message. 
- A timeout. E.g., I have observed that a HTTP connection usually dies at 60s with Trin. Sometimes a message comes through (with the content or with the no-content message at ~50 seconds. So it seems plausible that for some content a timeout could occur despite the content existing but being inaccessible within the timeout. 

Current behaviour: Timout is logged as an error in `glados-audit`

I am inclined to keep this behaviour.

**Comment by pipermerriam** [comment]
I think that treating them as errors/missing is appropriate.
